<?php
namespace application\libraries\RedisKeyConstants;

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


$GLOBALS['RedisKey_CONSTANTS']['NULL_VALUE'] = "null";

$GLOBALS['RedisKey_CONSTANTS']['RSCCOUNTY'] = "rscCounty";

$GLOBALS['RedisKey_CONSTANTS']['USER_PREFIX'] = "user_";

$GLOBALS['RedisKey_CONSTANTS']['BLACK_LIST_PREFIX'] = "h_user_black_list";

$GLOBALS['RedisKey_CONSTANTS']['ADVERT_INFO_PREFIX'] = "ADVERT_INFO_PREFIX";

$GLOBALS['RedisKey_CONSTANTS']['ADVERT_TOTAL_COUNT'] = "ADVERT_TOTAL_COUNT";


