<?php
namespace application\libraries\ConstConfig;

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


$GLOBALS['ConstConfig_CONSTANTS']['IDTYPE'] = array(
  3 => "护照",
  1 => "身份证",
  2 => "军官证",
);

$GLOBALS['ConstConfig_CONSTANTS']['RELATIONSHIP'] = array(
  1 => "家人",
  2 => "亲戚",
  3 => "朋友",
  0 => "本人",
);

$GLOBALS['ConstConfig_CONSTANTS']['GENDER'] = array(
  1 => "男",
  3 => "未知",
  2 => "女",
);

$GLOBALS['ConstConfig_CONSTANTS']['Hospital_Favorite_Type'] = 10;

$GLOBALS['ConstConfig_CONSTANTS']['Doctor_Favorite_Type'] = 12;


