/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.shalong.zhangpai.rsc.thrift.advertisement;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class GetAdvertisementShowOutput implements org.apache.thrift.TBase<GetAdvertisementShowOutput, GetAdvertisementShowOutput._Fields>, java.io.Serializable, Cloneable, Comparable<GetAdvertisementShowOutput> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GetAdvertisementShowOutput");

  private static final org.apache.thrift.protocol.TField RETURN_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("returnCode", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField AD_TITLE_FIELD_DESC = new org.apache.thrift.protocol.TField("adTitle", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField AD_DESCRIPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("adDescription", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField CREATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("createTime", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField AD_LOCATION_FIELD_DESC = new org.apache.thrift.protocol.TField("adLocation", org.apache.thrift.protocol.TType.I32, (short)6);
  private static final org.apache.thrift.protocol.TField IP_SINGLE_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("ipSingleNum", org.apache.thrift.protocol.TType.I32, (short)7);
  private static final org.apache.thrift.protocol.TField IP_MUCH_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("ipMuchNum", org.apache.thrift.protocol.TType.I32, (short)8);
  private static final org.apache.thrift.protocol.TField ONLINE_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("onlineStatus", org.apache.thrift.protocol.TType.I32, (short)9);
  private static final org.apache.thrift.protocol.TField AUDIT_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("auditStatus", org.apache.thrift.protocol.TType.I32, (short)10);
  private static final org.apache.thrift.protocol.TField AD_IMAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("adImage", org.apache.thrift.protocol.TType.STRING, (short)11);
  private static final org.apache.thrift.protocol.TField AD_LINK_FIELD_DESC = new org.apache.thrift.protocol.TField("adLink", org.apache.thrift.protocol.TType.STRING, (short)12);
  private static final org.apache.thrift.protocol.TField AD_CONTENT_FIELD_DESC = new org.apache.thrift.protocol.TField("adContent", org.apache.thrift.protocol.TType.STRING, (short)13);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new GetAdvertisementShowOutputStandardSchemeFactory());
    schemes.put(TupleScheme.class, new GetAdvertisementShowOutputTupleSchemeFactory());
  }

  public int returnCode; // required
  public int id; // required
  public String adTitle; // required
  public String adDescription; // required
  public String createTime; // required
  public int adLocation; // required
  public int ipSingleNum; // required
  public int ipMuchNum; // required
  public int onlineStatus; // required
  public int auditStatus; // required
  public String adImage; // required
  public String adLink; // required
  public String adContent; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RETURN_CODE((short)1, "returnCode"),
    ID((short)2, "id"),
    AD_TITLE((short)3, "adTitle"),
    AD_DESCRIPTION((short)4, "adDescription"),
    CREATE_TIME((short)5, "createTime"),
    AD_LOCATION((short)6, "adLocation"),
    IP_SINGLE_NUM((short)7, "ipSingleNum"),
    IP_MUCH_NUM((short)8, "ipMuchNum"),
    ONLINE_STATUS((short)9, "onlineStatus"),
    AUDIT_STATUS((short)10, "auditStatus"),
    AD_IMAGE((short)11, "adImage"),
    AD_LINK((short)12, "adLink"),
    AD_CONTENT((short)13, "adContent");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RETURN_CODE
          return RETURN_CODE;
        case 2: // ID
          return ID;
        case 3: // AD_TITLE
          return AD_TITLE;
        case 4: // AD_DESCRIPTION
          return AD_DESCRIPTION;
        case 5: // CREATE_TIME
          return CREATE_TIME;
        case 6: // AD_LOCATION
          return AD_LOCATION;
        case 7: // IP_SINGLE_NUM
          return IP_SINGLE_NUM;
        case 8: // IP_MUCH_NUM
          return IP_MUCH_NUM;
        case 9: // ONLINE_STATUS
          return ONLINE_STATUS;
        case 10: // AUDIT_STATUS
          return AUDIT_STATUS;
        case 11: // AD_IMAGE
          return AD_IMAGE;
        case 12: // AD_LINK
          return AD_LINK;
        case 13: // AD_CONTENT
          return AD_CONTENT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RETURNCODE_ISSET_ID = 0;
  private static final int __ID_ISSET_ID = 1;
  private static final int __ADLOCATION_ISSET_ID = 2;
  private static final int __IPSINGLENUM_ISSET_ID = 3;
  private static final int __IPMUCHNUM_ISSET_ID = 4;
  private static final int __ONLINESTATUS_ISSET_ID = 5;
  private static final int __AUDITSTATUS_ISSET_ID = 6;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RETURN_CODE, new org.apache.thrift.meta_data.FieldMetaData("returnCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.AD_TITLE, new org.apache.thrift.meta_data.FieldMetaData("adTitle", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.AD_DESCRIPTION, new org.apache.thrift.meta_data.FieldMetaData("adDescription", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CREATE_TIME, new org.apache.thrift.meta_data.FieldMetaData("createTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.AD_LOCATION, new org.apache.thrift.meta_data.FieldMetaData("adLocation", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.IP_SINGLE_NUM, new org.apache.thrift.meta_data.FieldMetaData("ipSingleNum", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.IP_MUCH_NUM, new org.apache.thrift.meta_data.FieldMetaData("ipMuchNum", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ONLINE_STATUS, new org.apache.thrift.meta_data.FieldMetaData("onlineStatus", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.AUDIT_STATUS, new org.apache.thrift.meta_data.FieldMetaData("auditStatus", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.AD_IMAGE, new org.apache.thrift.meta_data.FieldMetaData("adImage", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.AD_LINK, new org.apache.thrift.meta_data.FieldMetaData("adLink", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.AD_CONTENT, new org.apache.thrift.meta_data.FieldMetaData("adContent", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GetAdvertisementShowOutput.class, metaDataMap);
  }

  public GetAdvertisementShowOutput() {
  }

  public GetAdvertisementShowOutput(
    int returnCode,
    int id,
    String adTitle,
    String adDescription,
    String createTime,
    int adLocation,
    int ipSingleNum,
    int ipMuchNum,
    int onlineStatus,
    int auditStatus,
    String adImage,
    String adLink,
    String adContent)
  {
    this();
    this.returnCode = returnCode;
    setReturnCodeIsSet(true);
    this.id = id;
    setIdIsSet(true);
    this.adTitle = adTitle;
    this.adDescription = adDescription;
    this.createTime = createTime;
    this.adLocation = adLocation;
    setAdLocationIsSet(true);
    this.ipSingleNum = ipSingleNum;
    setIpSingleNumIsSet(true);
    this.ipMuchNum = ipMuchNum;
    setIpMuchNumIsSet(true);
    this.onlineStatus = onlineStatus;
    setOnlineStatusIsSet(true);
    this.auditStatus = auditStatus;
    setAuditStatusIsSet(true);
    this.adImage = adImage;
    this.adLink = adLink;
    this.adContent = adContent;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GetAdvertisementShowOutput(GetAdvertisementShowOutput other) {
    __isset_bitfield = other.__isset_bitfield;
    this.returnCode = other.returnCode;
    this.id = other.id;
    if (other.isSetAdTitle()) {
      this.adTitle = other.adTitle;
    }
    if (other.isSetAdDescription()) {
      this.adDescription = other.adDescription;
    }
    if (other.isSetCreateTime()) {
      this.createTime = other.createTime;
    }
    this.adLocation = other.adLocation;
    this.ipSingleNum = other.ipSingleNum;
    this.ipMuchNum = other.ipMuchNum;
    this.onlineStatus = other.onlineStatus;
    this.auditStatus = other.auditStatus;
    if (other.isSetAdImage()) {
      this.adImage = other.adImage;
    }
    if (other.isSetAdLink()) {
      this.adLink = other.adLink;
    }
    if (other.isSetAdContent()) {
      this.adContent = other.adContent;
    }
  }

  public GetAdvertisementShowOutput deepCopy() {
    return new GetAdvertisementShowOutput(this);
  }

  @Override
  public void clear() {
    setReturnCodeIsSet(false);
    this.returnCode = 0;
    setIdIsSet(false);
    this.id = 0;
    this.adTitle = null;
    this.adDescription = null;
    this.createTime = null;
    setAdLocationIsSet(false);
    this.adLocation = 0;
    setIpSingleNumIsSet(false);
    this.ipSingleNum = 0;
    setIpMuchNumIsSet(false);
    this.ipMuchNum = 0;
    setOnlineStatusIsSet(false);
    this.onlineStatus = 0;
    setAuditStatusIsSet(false);
    this.auditStatus = 0;
    this.adImage = null;
    this.adLink = null;
    this.adContent = null;
  }

  public int getReturnCode() {
    return this.returnCode;
  }

  public GetAdvertisementShowOutput setReturnCode(int returnCode) {
    this.returnCode = returnCode;
    setReturnCodeIsSet(true);
    return this;
  }

  public void unsetReturnCode() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __RETURNCODE_ISSET_ID);
  }

  /** Returns true if field returnCode is set (has been assigned a value) and false otherwise */
  public boolean isSetReturnCode() {
    return EncodingUtils.testBit(__isset_bitfield, __RETURNCODE_ISSET_ID);
  }

  public void setReturnCodeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __RETURNCODE_ISSET_ID, value);
  }

  public int getId() {
    return this.id;
  }

  public GetAdvertisementShowOutput setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public String getAdTitle() {
    return this.adTitle;
  }

  public GetAdvertisementShowOutput setAdTitle(String adTitle) {
    this.adTitle = adTitle;
    return this;
  }

  public void unsetAdTitle() {
    this.adTitle = null;
  }

  /** Returns true if field adTitle is set (has been assigned a value) and false otherwise */
  public boolean isSetAdTitle() {
    return this.adTitle != null;
  }

  public void setAdTitleIsSet(boolean value) {
    if (!value) {
      this.adTitle = null;
    }
  }

  public String getAdDescription() {
    return this.adDescription;
  }

  public GetAdvertisementShowOutput setAdDescription(String adDescription) {
    this.adDescription = adDescription;
    return this;
  }

  public void unsetAdDescription() {
    this.adDescription = null;
  }

  /** Returns true if field adDescription is set (has been assigned a value) and false otherwise */
  public boolean isSetAdDescription() {
    return this.adDescription != null;
  }

  public void setAdDescriptionIsSet(boolean value) {
    if (!value) {
      this.adDescription = null;
    }
  }

  public String getCreateTime() {
    return this.createTime;
  }

  public GetAdvertisementShowOutput setCreateTime(String createTime) {
    this.createTime = createTime;
    return this;
  }

  public void unsetCreateTime() {
    this.createTime = null;
  }

  /** Returns true if field createTime is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateTime() {
    return this.createTime != null;
  }

  public void setCreateTimeIsSet(boolean value) {
    if (!value) {
      this.createTime = null;
    }
  }

  public int getAdLocation() {
    return this.adLocation;
  }

  public GetAdvertisementShowOutput setAdLocation(int adLocation) {
    this.adLocation = adLocation;
    setAdLocationIsSet(true);
    return this;
  }

  public void unsetAdLocation() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ADLOCATION_ISSET_ID);
  }

  /** Returns true if field adLocation is set (has been assigned a value) and false otherwise */
  public boolean isSetAdLocation() {
    return EncodingUtils.testBit(__isset_bitfield, __ADLOCATION_ISSET_ID);
  }

  public void setAdLocationIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ADLOCATION_ISSET_ID, value);
  }

  public int getIpSingleNum() {
    return this.ipSingleNum;
  }

  public GetAdvertisementShowOutput setIpSingleNum(int ipSingleNum) {
    this.ipSingleNum = ipSingleNum;
    setIpSingleNumIsSet(true);
    return this;
  }

  public void unsetIpSingleNum() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __IPSINGLENUM_ISSET_ID);
  }

  /** Returns true if field ipSingleNum is set (has been assigned a value) and false otherwise */
  public boolean isSetIpSingleNum() {
    return EncodingUtils.testBit(__isset_bitfield, __IPSINGLENUM_ISSET_ID);
  }

  public void setIpSingleNumIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __IPSINGLENUM_ISSET_ID, value);
  }

  public int getIpMuchNum() {
    return this.ipMuchNum;
  }

  public GetAdvertisementShowOutput setIpMuchNum(int ipMuchNum) {
    this.ipMuchNum = ipMuchNum;
    setIpMuchNumIsSet(true);
    return this;
  }

  public void unsetIpMuchNum() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __IPMUCHNUM_ISSET_ID);
  }

  /** Returns true if field ipMuchNum is set (has been assigned a value) and false otherwise */
  public boolean isSetIpMuchNum() {
    return EncodingUtils.testBit(__isset_bitfield, __IPMUCHNUM_ISSET_ID);
  }

  public void setIpMuchNumIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __IPMUCHNUM_ISSET_ID, value);
  }

  public int getOnlineStatus() {
    return this.onlineStatus;
  }

  public GetAdvertisementShowOutput setOnlineStatus(int onlineStatus) {
    this.onlineStatus = onlineStatus;
    setOnlineStatusIsSet(true);
    return this;
  }

  public void unsetOnlineStatus() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ONLINESTATUS_ISSET_ID);
  }

  /** Returns true if field onlineStatus is set (has been assigned a value) and false otherwise */
  public boolean isSetOnlineStatus() {
    return EncodingUtils.testBit(__isset_bitfield, __ONLINESTATUS_ISSET_ID);
  }

  public void setOnlineStatusIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ONLINESTATUS_ISSET_ID, value);
  }

  public int getAuditStatus() {
    return this.auditStatus;
  }

  public GetAdvertisementShowOutput setAuditStatus(int auditStatus) {
    this.auditStatus = auditStatus;
    setAuditStatusIsSet(true);
    return this;
  }

  public void unsetAuditStatus() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __AUDITSTATUS_ISSET_ID);
  }

  /** Returns true if field auditStatus is set (has been assigned a value) and false otherwise */
  public boolean isSetAuditStatus() {
    return EncodingUtils.testBit(__isset_bitfield, __AUDITSTATUS_ISSET_ID);
  }

  public void setAuditStatusIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __AUDITSTATUS_ISSET_ID, value);
  }

  public String getAdImage() {
    return this.adImage;
  }

  public GetAdvertisementShowOutput setAdImage(String adImage) {
    this.adImage = adImage;
    return this;
  }

  public void unsetAdImage() {
    this.adImage = null;
  }

  /** Returns true if field adImage is set (has been assigned a value) and false otherwise */
  public boolean isSetAdImage() {
    return this.adImage != null;
  }

  public void setAdImageIsSet(boolean value) {
    if (!value) {
      this.adImage = null;
    }
  }

  public String getAdLink() {
    return this.adLink;
  }

  public GetAdvertisementShowOutput setAdLink(String adLink) {
    this.adLink = adLink;
    return this;
  }

  public void unsetAdLink() {
    this.adLink = null;
  }

  /** Returns true if field adLink is set (has been assigned a value) and false otherwise */
  public boolean isSetAdLink() {
    return this.adLink != null;
  }

  public void setAdLinkIsSet(boolean value) {
    if (!value) {
      this.adLink = null;
    }
  }

  public String getAdContent() {
    return this.adContent;
  }

  public GetAdvertisementShowOutput setAdContent(String adContent) {
    this.adContent = adContent;
    return this;
  }

  public void unsetAdContent() {
    this.adContent = null;
  }

  /** Returns true if field adContent is set (has been assigned a value) and false otherwise */
  public boolean isSetAdContent() {
    return this.adContent != null;
  }

  public void setAdContentIsSet(boolean value) {
    if (!value) {
      this.adContent = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RETURN_CODE:
      if (value == null) {
        unsetReturnCode();
      } else {
        setReturnCode((Integer)value);
      }
      break;

    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((Integer)value);
      }
      break;

    case AD_TITLE:
      if (value == null) {
        unsetAdTitle();
      } else {
        setAdTitle((String)value);
      }
      break;

    case AD_DESCRIPTION:
      if (value == null) {
        unsetAdDescription();
      } else {
        setAdDescription((String)value);
      }
      break;

    case CREATE_TIME:
      if (value == null) {
        unsetCreateTime();
      } else {
        setCreateTime((String)value);
      }
      break;

    case AD_LOCATION:
      if (value == null) {
        unsetAdLocation();
      } else {
        setAdLocation((Integer)value);
      }
      break;

    case IP_SINGLE_NUM:
      if (value == null) {
        unsetIpSingleNum();
      } else {
        setIpSingleNum((Integer)value);
      }
      break;

    case IP_MUCH_NUM:
      if (value == null) {
        unsetIpMuchNum();
      } else {
        setIpMuchNum((Integer)value);
      }
      break;

    case ONLINE_STATUS:
      if (value == null) {
        unsetOnlineStatus();
      } else {
        setOnlineStatus((Integer)value);
      }
      break;

    case AUDIT_STATUS:
      if (value == null) {
        unsetAuditStatus();
      } else {
        setAuditStatus((Integer)value);
      }
      break;

    case AD_IMAGE:
      if (value == null) {
        unsetAdImage();
      } else {
        setAdImage((String)value);
      }
      break;

    case AD_LINK:
      if (value == null) {
        unsetAdLink();
      } else {
        setAdLink((String)value);
      }
      break;

    case AD_CONTENT:
      if (value == null) {
        unsetAdContent();
      } else {
        setAdContent((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RETURN_CODE:
      return Integer.valueOf(getReturnCode());

    case ID:
      return Integer.valueOf(getId());

    case AD_TITLE:
      return getAdTitle();

    case AD_DESCRIPTION:
      return getAdDescription();

    case CREATE_TIME:
      return getCreateTime();

    case AD_LOCATION:
      return Integer.valueOf(getAdLocation());

    case IP_SINGLE_NUM:
      return Integer.valueOf(getIpSingleNum());

    case IP_MUCH_NUM:
      return Integer.valueOf(getIpMuchNum());

    case ONLINE_STATUS:
      return Integer.valueOf(getOnlineStatus());

    case AUDIT_STATUS:
      return Integer.valueOf(getAuditStatus());

    case AD_IMAGE:
      return getAdImage();

    case AD_LINK:
      return getAdLink();

    case AD_CONTENT:
      return getAdContent();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RETURN_CODE:
      return isSetReturnCode();
    case ID:
      return isSetId();
    case AD_TITLE:
      return isSetAdTitle();
    case AD_DESCRIPTION:
      return isSetAdDescription();
    case CREATE_TIME:
      return isSetCreateTime();
    case AD_LOCATION:
      return isSetAdLocation();
    case IP_SINGLE_NUM:
      return isSetIpSingleNum();
    case IP_MUCH_NUM:
      return isSetIpMuchNum();
    case ONLINE_STATUS:
      return isSetOnlineStatus();
    case AUDIT_STATUS:
      return isSetAuditStatus();
    case AD_IMAGE:
      return isSetAdImage();
    case AD_LINK:
      return isSetAdLink();
    case AD_CONTENT:
      return isSetAdContent();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof GetAdvertisementShowOutput)
      return this.equals((GetAdvertisementShowOutput)that);
    return false;
  }

  public boolean equals(GetAdvertisementShowOutput that) {
    if (that == null)
      return false;

    boolean this_present_returnCode = true;
    boolean that_present_returnCode = true;
    if (this_present_returnCode || that_present_returnCode) {
      if (!(this_present_returnCode && that_present_returnCode))
        return false;
      if (this.returnCode != that.returnCode)
        return false;
    }

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_adTitle = true && this.isSetAdTitle();
    boolean that_present_adTitle = true && that.isSetAdTitle();
    if (this_present_adTitle || that_present_adTitle) {
      if (!(this_present_adTitle && that_present_adTitle))
        return false;
      if (!this.adTitle.equals(that.adTitle))
        return false;
    }

    boolean this_present_adDescription = true && this.isSetAdDescription();
    boolean that_present_adDescription = true && that.isSetAdDescription();
    if (this_present_adDescription || that_present_adDescription) {
      if (!(this_present_adDescription && that_present_adDescription))
        return false;
      if (!this.adDescription.equals(that.adDescription))
        return false;
    }

    boolean this_present_createTime = true && this.isSetCreateTime();
    boolean that_present_createTime = true && that.isSetCreateTime();
    if (this_present_createTime || that_present_createTime) {
      if (!(this_present_createTime && that_present_createTime))
        return false;
      if (!this.createTime.equals(that.createTime))
        return false;
    }

    boolean this_present_adLocation = true;
    boolean that_present_adLocation = true;
    if (this_present_adLocation || that_present_adLocation) {
      if (!(this_present_adLocation && that_present_adLocation))
        return false;
      if (this.adLocation != that.adLocation)
        return false;
    }

    boolean this_present_ipSingleNum = true;
    boolean that_present_ipSingleNum = true;
    if (this_present_ipSingleNum || that_present_ipSingleNum) {
      if (!(this_present_ipSingleNum && that_present_ipSingleNum))
        return false;
      if (this.ipSingleNum != that.ipSingleNum)
        return false;
    }

    boolean this_present_ipMuchNum = true;
    boolean that_present_ipMuchNum = true;
    if (this_present_ipMuchNum || that_present_ipMuchNum) {
      if (!(this_present_ipMuchNum && that_present_ipMuchNum))
        return false;
      if (this.ipMuchNum != that.ipMuchNum)
        return false;
    }

    boolean this_present_onlineStatus = true;
    boolean that_present_onlineStatus = true;
    if (this_present_onlineStatus || that_present_onlineStatus) {
      if (!(this_present_onlineStatus && that_present_onlineStatus))
        return false;
      if (this.onlineStatus != that.onlineStatus)
        return false;
    }

    boolean this_present_auditStatus = true;
    boolean that_present_auditStatus = true;
    if (this_present_auditStatus || that_present_auditStatus) {
      if (!(this_present_auditStatus && that_present_auditStatus))
        return false;
      if (this.auditStatus != that.auditStatus)
        return false;
    }

    boolean this_present_adImage = true && this.isSetAdImage();
    boolean that_present_adImage = true && that.isSetAdImage();
    if (this_present_adImage || that_present_adImage) {
      if (!(this_present_adImage && that_present_adImage))
        return false;
      if (!this.adImage.equals(that.adImage))
        return false;
    }

    boolean this_present_adLink = true && this.isSetAdLink();
    boolean that_present_adLink = true && that.isSetAdLink();
    if (this_present_adLink || that_present_adLink) {
      if (!(this_present_adLink && that_present_adLink))
        return false;
      if (!this.adLink.equals(that.adLink))
        return false;
    }

    boolean this_present_adContent = true && this.isSetAdContent();
    boolean that_present_adContent = true && that.isSetAdContent();
    if (this_present_adContent || that_present_adContent) {
      if (!(this_present_adContent && that_present_adContent))
        return false;
      if (!this.adContent.equals(that.adContent))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(GetAdvertisementShowOutput other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetReturnCode()).compareTo(other.isSetReturnCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReturnCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.returnCode, other.returnCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAdTitle()).compareTo(other.isSetAdTitle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAdTitle()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.adTitle, other.adTitle);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAdDescription()).compareTo(other.isSetAdDescription());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAdDescription()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.adDescription, other.adDescription);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreateTime()).compareTo(other.isSetCreateTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createTime, other.createTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAdLocation()).compareTo(other.isSetAdLocation());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAdLocation()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.adLocation, other.adLocation);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIpSingleNum()).compareTo(other.isSetIpSingleNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIpSingleNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ipSingleNum, other.ipSingleNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIpMuchNum()).compareTo(other.isSetIpMuchNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIpMuchNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ipMuchNum, other.ipMuchNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOnlineStatus()).compareTo(other.isSetOnlineStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOnlineStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.onlineStatus, other.onlineStatus);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAuditStatus()).compareTo(other.isSetAuditStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAuditStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.auditStatus, other.auditStatus);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAdImage()).compareTo(other.isSetAdImage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAdImage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.adImage, other.adImage);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAdLink()).compareTo(other.isSetAdLink());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAdLink()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.adLink, other.adLink);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAdContent()).compareTo(other.isSetAdContent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAdContent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.adContent, other.adContent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("GetAdvertisementShowOutput(");
    boolean first = true;

    sb.append("returnCode:");
    sb.append(this.returnCode);
    first = false;
    if (!first) sb.append(", ");
    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("adTitle:");
    if (this.adTitle == null) {
      sb.append("null");
    } else {
      sb.append(this.adTitle);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("adDescription:");
    if (this.adDescription == null) {
      sb.append("null");
    } else {
      sb.append(this.adDescription);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("createTime:");
    if (this.createTime == null) {
      sb.append("null");
    } else {
      sb.append(this.createTime);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("adLocation:");
    sb.append(this.adLocation);
    first = false;
    if (!first) sb.append(", ");
    sb.append("ipSingleNum:");
    sb.append(this.ipSingleNum);
    first = false;
    if (!first) sb.append(", ");
    sb.append("ipMuchNum:");
    sb.append(this.ipMuchNum);
    first = false;
    if (!first) sb.append(", ");
    sb.append("onlineStatus:");
    sb.append(this.onlineStatus);
    first = false;
    if (!first) sb.append(", ");
    sb.append("auditStatus:");
    sb.append(this.auditStatus);
    first = false;
    if (!first) sb.append(", ");
    sb.append("adImage:");
    if (this.adImage == null) {
      sb.append("null");
    } else {
      sb.append(this.adImage);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("adLink:");
    if (this.adLink == null) {
      sb.append("null");
    } else {
      sb.append(this.adLink);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("adContent:");
    if (this.adContent == null) {
      sb.append("null");
    } else {
      sb.append(this.adContent);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GetAdvertisementShowOutputStandardSchemeFactory implements SchemeFactory {
    public GetAdvertisementShowOutputStandardScheme getScheme() {
      return new GetAdvertisementShowOutputStandardScheme();
    }
  }

  private static class GetAdvertisementShowOutputStandardScheme extends StandardScheme<GetAdvertisementShowOutput> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, GetAdvertisementShowOutput struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RETURN_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.returnCode = iprot.readI32();
              struct.setReturnCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // AD_TITLE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.adTitle = iprot.readString();
              struct.setAdTitleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // AD_DESCRIPTION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.adDescription = iprot.readString();
              struct.setAdDescriptionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // CREATE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.createTime = iprot.readString();
              struct.setCreateTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // AD_LOCATION
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.adLocation = iprot.readI32();
              struct.setAdLocationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // IP_SINGLE_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.ipSingleNum = iprot.readI32();
              struct.setIpSingleNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // IP_MUCH_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.ipMuchNum = iprot.readI32();
              struct.setIpMuchNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // ONLINE_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.onlineStatus = iprot.readI32();
              struct.setOnlineStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // AUDIT_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.auditStatus = iprot.readI32();
              struct.setAuditStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // AD_IMAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.adImage = iprot.readString();
              struct.setAdImageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // AD_LINK
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.adLink = iprot.readString();
              struct.setAdLinkIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // AD_CONTENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.adContent = iprot.readString();
              struct.setAdContentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, GetAdvertisementShowOutput struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(RETURN_CODE_FIELD_DESC);
      oprot.writeI32(struct.returnCode);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(struct.id);
      oprot.writeFieldEnd();
      if (struct.adTitle != null) {
        oprot.writeFieldBegin(AD_TITLE_FIELD_DESC);
        oprot.writeString(struct.adTitle);
        oprot.writeFieldEnd();
      }
      if (struct.adDescription != null) {
        oprot.writeFieldBegin(AD_DESCRIPTION_FIELD_DESC);
        oprot.writeString(struct.adDescription);
        oprot.writeFieldEnd();
      }
      if (struct.createTime != null) {
        oprot.writeFieldBegin(CREATE_TIME_FIELD_DESC);
        oprot.writeString(struct.createTime);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(AD_LOCATION_FIELD_DESC);
      oprot.writeI32(struct.adLocation);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(IP_SINGLE_NUM_FIELD_DESC);
      oprot.writeI32(struct.ipSingleNum);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(IP_MUCH_NUM_FIELD_DESC);
      oprot.writeI32(struct.ipMuchNum);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ONLINE_STATUS_FIELD_DESC);
      oprot.writeI32(struct.onlineStatus);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(AUDIT_STATUS_FIELD_DESC);
      oprot.writeI32(struct.auditStatus);
      oprot.writeFieldEnd();
      if (struct.adImage != null) {
        oprot.writeFieldBegin(AD_IMAGE_FIELD_DESC);
        oprot.writeString(struct.adImage);
        oprot.writeFieldEnd();
      }
      if (struct.adLink != null) {
        oprot.writeFieldBegin(AD_LINK_FIELD_DESC);
        oprot.writeString(struct.adLink);
        oprot.writeFieldEnd();
      }
      if (struct.adContent != null) {
        oprot.writeFieldBegin(AD_CONTENT_FIELD_DESC);
        oprot.writeString(struct.adContent);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GetAdvertisementShowOutputTupleSchemeFactory implements SchemeFactory {
    public GetAdvertisementShowOutputTupleScheme getScheme() {
      return new GetAdvertisementShowOutputTupleScheme();
    }
  }

  private static class GetAdvertisementShowOutputTupleScheme extends TupleScheme<GetAdvertisementShowOutput> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, GetAdvertisementShowOutput struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetReturnCode()) {
        optionals.set(0);
      }
      if (struct.isSetId()) {
        optionals.set(1);
      }
      if (struct.isSetAdTitle()) {
        optionals.set(2);
      }
      if (struct.isSetAdDescription()) {
        optionals.set(3);
      }
      if (struct.isSetCreateTime()) {
        optionals.set(4);
      }
      if (struct.isSetAdLocation()) {
        optionals.set(5);
      }
      if (struct.isSetIpSingleNum()) {
        optionals.set(6);
      }
      if (struct.isSetIpMuchNum()) {
        optionals.set(7);
      }
      if (struct.isSetOnlineStatus()) {
        optionals.set(8);
      }
      if (struct.isSetAuditStatus()) {
        optionals.set(9);
      }
      if (struct.isSetAdImage()) {
        optionals.set(10);
      }
      if (struct.isSetAdLink()) {
        optionals.set(11);
      }
      if (struct.isSetAdContent()) {
        optionals.set(12);
      }
      oprot.writeBitSet(optionals, 13);
      if (struct.isSetReturnCode()) {
        oprot.writeI32(struct.returnCode);
      }
      if (struct.isSetId()) {
        oprot.writeI32(struct.id);
      }
      if (struct.isSetAdTitle()) {
        oprot.writeString(struct.adTitle);
      }
      if (struct.isSetAdDescription()) {
        oprot.writeString(struct.adDescription);
      }
      if (struct.isSetCreateTime()) {
        oprot.writeString(struct.createTime);
      }
      if (struct.isSetAdLocation()) {
        oprot.writeI32(struct.adLocation);
      }
      if (struct.isSetIpSingleNum()) {
        oprot.writeI32(struct.ipSingleNum);
      }
      if (struct.isSetIpMuchNum()) {
        oprot.writeI32(struct.ipMuchNum);
      }
      if (struct.isSetOnlineStatus()) {
        oprot.writeI32(struct.onlineStatus);
      }
      if (struct.isSetAuditStatus()) {
        oprot.writeI32(struct.auditStatus);
      }
      if (struct.isSetAdImage()) {
        oprot.writeString(struct.adImage);
      }
      if (struct.isSetAdLink()) {
        oprot.writeString(struct.adLink);
      }
      if (struct.isSetAdContent()) {
        oprot.writeString(struct.adContent);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, GetAdvertisementShowOutput struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(13);
      if (incoming.get(0)) {
        struct.returnCode = iprot.readI32();
        struct.setReturnCodeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.id = iprot.readI32();
        struct.setIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.adTitle = iprot.readString();
        struct.setAdTitleIsSet(true);
      }
      if (incoming.get(3)) {
        struct.adDescription = iprot.readString();
        struct.setAdDescriptionIsSet(true);
      }
      if (incoming.get(4)) {
        struct.createTime = iprot.readString();
        struct.setCreateTimeIsSet(true);
      }
      if (incoming.get(5)) {
        struct.adLocation = iprot.readI32();
        struct.setAdLocationIsSet(true);
      }
      if (incoming.get(6)) {
        struct.ipSingleNum = iprot.readI32();
        struct.setIpSingleNumIsSet(true);
      }
      if (incoming.get(7)) {
        struct.ipMuchNum = iprot.readI32();
        struct.setIpMuchNumIsSet(true);
      }
      if (incoming.get(8)) {
        struct.onlineStatus = iprot.readI32();
        struct.setOnlineStatusIsSet(true);
      }
      if (incoming.get(9)) {
        struct.auditStatus = iprot.readI32();
        struct.setAuditStatusIsSet(true);
      }
      if (incoming.get(10)) {
        struct.adImage = iprot.readString();
        struct.setAdImageIsSet(true);
      }
      if (incoming.get(11)) {
        struct.adLink = iprot.readString();
        struct.setAdLinkIsSet(true);
      }
      if (incoming.get(12)) {
        struct.adContent = iprot.readString();
        struct.setAdContentIsSet(true);
      }
    }
  }

}

