/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface Advertisement : NSObject <TBase, NSCoding> {
  int32_t __id;
  NSString * __adTitle;
  NSString * __adDescription;
  NSString * __createTime;
  int32_t __adLocation;
  int32_t __ipSingleNum;
  int32_t __ipMuchNum;
  int32_t __onlineStatus;
  int32_t __auditStatus;
  NSString * __adImage;
  NSString * __adLink;
  NSString * __adContent;

  BOOL __id_isset;
  BOOL __adTitle_isset;
  BOOL __adDescription_isset;
  BOOL __createTime_isset;
  BOOL __adLocation_isset;
  BOOL __ipSingleNum_isset;
  BOOL __ipMuchNum_isset;
  BOOL __onlineStatus_isset;
  BOOL __auditStatus_isset;
  BOOL __adImage_isset;
  BOOL __adLink_isset;
  BOOL __adContent_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, retain, getter=adTitle, setter=setAdTitle:) NSString * adTitle;
@property (nonatomic, retain, getter=adDescription, setter=setAdDescription:) NSString * adDescription;
@property (nonatomic, retain, getter=createTime, setter=setCreateTime:) NSString * createTime;
@property (nonatomic, getter=adLocation, setter=setAdLocation:) int32_t adLocation;
@property (nonatomic, getter=ipSingleNum, setter=setIpSingleNum:) int32_t ipSingleNum;
@property (nonatomic, getter=ipMuchNum, setter=setIpMuchNum:) int32_t ipMuchNum;
@property (nonatomic, getter=onlineStatus, setter=setOnlineStatus:) int32_t onlineStatus;
@property (nonatomic, getter=auditStatus, setter=setAuditStatus:) int32_t auditStatus;
@property (nonatomic, retain, getter=adImage, setter=setAdImage:) NSString * adImage;
@property (nonatomic, retain, getter=adLink, setter=setAdLink:) NSString * adLink;
@property (nonatomic, retain, getter=adContent, setter=setAdContent:) NSString * adContent;
#endif

- (id) init;
- (id) initWithId: (int32_t) id adTitle: (NSString *) adTitle adDescription: (NSString *) adDescription createTime: (NSString *) createTime adLocation: (int32_t) adLocation ipSingleNum: (int32_t) ipSingleNum ipMuchNum: (int32_t) ipMuchNum onlineStatus: (int32_t) onlineStatus auditStatus: (int32_t) auditStatus adImage: (NSString *) adImage adLink: (NSString *) adLink adContent: (NSString *) adContent;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) adTitle;
- (void) setAdTitle: (NSString *) adTitle;
#endif
- (BOOL) adTitleIsSet;

#if !__has_feature(objc_arc)
- (NSString *) adDescription;
- (void) setAdDescription: (NSString *) adDescription;
#endif
- (BOOL) adDescriptionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) createTime;
- (void) setCreateTime: (NSString *) createTime;
#endif
- (BOOL) createTimeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) adLocation;
- (void) setAdLocation: (int32_t) adLocation;
#endif
- (BOOL) adLocationIsSet;

#if !__has_feature(objc_arc)
- (int32_t) ipSingleNum;
- (void) setIpSingleNum: (int32_t) ipSingleNum;
#endif
- (BOOL) ipSingleNumIsSet;

#if !__has_feature(objc_arc)
- (int32_t) ipMuchNum;
- (void) setIpMuchNum: (int32_t) ipMuchNum;
#endif
- (BOOL) ipMuchNumIsSet;

#if !__has_feature(objc_arc)
- (int32_t) onlineStatus;
- (void) setOnlineStatus: (int32_t) onlineStatus;
#endif
- (BOOL) onlineStatusIsSet;

#if !__has_feature(objc_arc)
- (int32_t) auditStatus;
- (void) setAuditStatus: (int32_t) auditStatus;
#endif
- (BOOL) auditStatusIsSet;

#if !__has_feature(objc_arc)
- (NSString *) adImage;
- (void) setAdImage: (NSString *) adImage;
#endif
- (BOOL) adImageIsSet;

#if !__has_feature(objc_arc)
- (NSString *) adLink;
- (void) setAdLink: (NSString *) adLink;
#endif
- (BOOL) adLinkIsSet;

#if !__has_feature(objc_arc)
- (NSString *) adContent;
- (void) setAdContent: (NSString *) adContent;
#endif
- (BOOL) adContentIsSet;

@end

@interface GetAdvertisementInput : NSObject <TBase, NSCoding> {
  int32_t __id;
  NSString * __version;

  BOOL __id_isset;
  BOOL __version_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, retain, getter=version, setter=setVersion:) NSString * version;
#endif

- (id) init;
- (id) initWithId: (int32_t) id version: (NSString *) version;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) version;
- (void) setVersion: (NSString *) version;
#endif
- (BOOL) versionIsSet;

@end

@interface GetAdvertisementOutput : NSObject <TBase, NSCoding> {
  int32_t __returnCode;
  Advertisement * __advertisement;

  BOOL __returnCode_isset;
  BOOL __advertisement_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=returnCode, setter=setReturnCode:) int32_t returnCode;
@property (nonatomic, retain, getter=advertisement, setter=setAdvertisement:) Advertisement * advertisement;
#endif

- (id) init;
- (id) initWithReturnCode: (int32_t) returnCode advertisement: (Advertisement *) advertisement;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) returnCode;
- (void) setReturnCode: (int32_t) returnCode;
#endif
- (BOOL) returnCodeIsSet;

#if !__has_feature(objc_arc)
- (Advertisement *) advertisement;
- (void) setAdvertisement: (Advertisement *) advertisement;
#endif
- (BOOL) advertisementIsSet;

@end

@interface GetAdvertisementShowOutput : NSObject <TBase, NSCoding> {
  int32_t __returnCode;
  int32_t __id;
  NSString * __adTitle;
  NSString * __adDescription;
  NSString * __createTime;
  int32_t __adLocation;
  int32_t __ipSingleNum;
  int32_t __ipMuchNum;
  int32_t __onlineStatus;
  int32_t __auditStatus;
  NSString * __adImage;
  NSString * __adLink;
  NSString * __adContent;

  BOOL __returnCode_isset;
  BOOL __id_isset;
  BOOL __adTitle_isset;
  BOOL __adDescription_isset;
  BOOL __createTime_isset;
  BOOL __adLocation_isset;
  BOOL __ipSingleNum_isset;
  BOOL __ipMuchNum_isset;
  BOOL __onlineStatus_isset;
  BOOL __auditStatus_isset;
  BOOL __adImage_isset;
  BOOL __adLink_isset;
  BOOL __adContent_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=returnCode, setter=setReturnCode:) int32_t returnCode;
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, retain, getter=adTitle, setter=setAdTitle:) NSString * adTitle;
@property (nonatomic, retain, getter=adDescription, setter=setAdDescription:) NSString * adDescription;
@property (nonatomic, retain, getter=createTime, setter=setCreateTime:) NSString * createTime;
@property (nonatomic, getter=adLocation, setter=setAdLocation:) int32_t adLocation;
@property (nonatomic, getter=ipSingleNum, setter=setIpSingleNum:) int32_t ipSingleNum;
@property (nonatomic, getter=ipMuchNum, setter=setIpMuchNum:) int32_t ipMuchNum;
@property (nonatomic, getter=onlineStatus, setter=setOnlineStatus:) int32_t onlineStatus;
@property (nonatomic, getter=auditStatus, setter=setAuditStatus:) int32_t auditStatus;
@property (nonatomic, retain, getter=adImage, setter=setAdImage:) NSString * adImage;
@property (nonatomic, retain, getter=adLink, setter=setAdLink:) NSString * adLink;
@property (nonatomic, retain, getter=adContent, setter=setAdContent:) NSString * adContent;
#endif

- (id) init;
- (id) initWithReturnCode: (int32_t) returnCode id: (int32_t) id adTitle: (NSString *) adTitle adDescription: (NSString *) adDescription createTime: (NSString *) createTime adLocation: (int32_t) adLocation ipSingleNum: (int32_t) ipSingleNum ipMuchNum: (int32_t) ipMuchNum onlineStatus: (int32_t) onlineStatus auditStatus: (int32_t) auditStatus adImage: (NSString *) adImage adLink: (NSString *) adLink adContent: (NSString *) adContent;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) returnCode;
- (void) setReturnCode: (int32_t) returnCode;
#endif
- (BOOL) returnCodeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) adTitle;
- (void) setAdTitle: (NSString *) adTitle;
#endif
- (BOOL) adTitleIsSet;

#if !__has_feature(objc_arc)
- (NSString *) adDescription;
- (void) setAdDescription: (NSString *) adDescription;
#endif
- (BOOL) adDescriptionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) createTime;
- (void) setCreateTime: (NSString *) createTime;
#endif
- (BOOL) createTimeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) adLocation;
- (void) setAdLocation: (int32_t) adLocation;
#endif
- (BOOL) adLocationIsSet;

#if !__has_feature(objc_arc)
- (int32_t) ipSingleNum;
- (void) setIpSingleNum: (int32_t) ipSingleNum;
#endif
- (BOOL) ipSingleNumIsSet;

#if !__has_feature(objc_arc)
- (int32_t) ipMuchNum;
- (void) setIpMuchNum: (int32_t) ipMuchNum;
#endif
- (BOOL) ipMuchNumIsSet;

#if !__has_feature(objc_arc)
- (int32_t) onlineStatus;
- (void) setOnlineStatus: (int32_t) onlineStatus;
#endif
- (BOOL) onlineStatusIsSet;

#if !__has_feature(objc_arc)
- (int32_t) auditStatus;
- (void) setAuditStatus: (int32_t) auditStatus;
#endif
- (BOOL) auditStatusIsSet;

#if !__has_feature(objc_arc)
- (NSString *) adImage;
- (void) setAdImage: (NSString *) adImage;
#endif
- (BOOL) adImageIsSet;

#if !__has_feature(objc_arc)
- (NSString *) adLink;
- (void) setAdLink: (NSString *) adLink;
#endif
- (BOOL) adLinkIsSet;

#if !__has_feature(objc_arc)
- (NSString *) adContent;
- (void) setAdContent: (NSString *) adContent;
#endif
- (BOOL) adContentIsSet;

@end

@protocol AdvertisementService <NSObject>
- (GetAdvertisementOutput *) getAdvertisementInfo: (GetAdvertisementInput *) input;  // throws TException
@end

@interface AdvertisementServiceClient : NSObject <AdvertisementService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface AdvertisementServiceProcessor : NSObject <TProcessor> {
  id <AdvertisementService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithAdvertisementService: (id <AdvertisementService>) service;
- (id<AdvertisementService>) service;
@end

@interface AdvertisementConstants : NSObject {
}
@end
