/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface ConstConfigConstants : NSObject {
}
+ (NSMutableDictionary *) IDTYPE;
+ (NSMutableDictionary *) RELATIONSHIP;
+ (NSMutableDictionary *) GENDER;
+ (int32_t) Hospital_Favorite_Type;
+ (int32_t) Doctor_Favorite_Type;
@end
