/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


#import "ConstConfig.h"

static NSMutableDictionary * IDTYPE;
static NSMutableDictionary * RELATIONSHIP;
static NSMutableDictionary * GENDER;
static int32_t Hospital_Favorite_Type = 10;
static int32_t Doctor_Favorite_Type = 12;

@implementation ConstConfigConstants
+ (void) initialize {
  IDTYPE = [[NSMutableDictionary alloc] initWithCapacity:3]; 
  [IDTYPE setObject:@"军官证" forKey:[NSNumber numberWithLong: 2]];
  [IDTYPE setObject:@"护照" forKey:[NSNumber numberWithLong: 3]];
  [IDTYPE setObject:@"身份证" forKey:[NSNumber numberWithLong: 1]];

;
  RELATIONSHIP = [[NSMutableDictionary alloc] initWithCapacity:4]; 
  [RELATIONSHIP setObject:@"本人" forKey:[NSNumber numberWithLong: 0]];
  [RELATIONSHIP setObject:@"家人" forKey:[NSNumber numberWithLong: 1]];
  [RELATIONSHIP setObject:@"朋友" forKey:[NSNumber numberWithLong: 3]];
  [RELATIONSHIP setObject:@"亲戚" forKey:[NSNumber numberWithLong: 2]];

;
  GENDER = [[NSMutableDictionary alloc] initWithCapacity:3]; 
  [GENDER setObject:@"未知" forKey:[NSNumber numberWithLong: 3]];
  [GENDER setObject:@"男" forKey:[NSNumber numberWithLong: 1]];
  [GENDER setObject:@"女" forKey:[NSNumber numberWithLong: 2]];

;
}
+ (NSMutableDictionary *) IDTYPE{
  return IDTYPE;
}
+ (NSMutableDictionary *) RELATIONSHIP{
  return RELATIONSHIP;
}
+ (NSMutableDictionary *) GENDER{
  return GENDER;
}
+ (int32_t) Hospital_Favorite_Type{
  return Hospital_Favorite_Type;
}
+ (int32_t) Doctor_Favorite_Type{
  return Doctor_Favorite_Type;
}
@end

