/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface RedisKeyConstants : NSObject {
}
+ (NSString *) NULL_VALUE;
+ (NSString *) RSCCOUNTY;
+ (NSString *) USER_PREFIX;
+ (NSString *) BLACK_LIST_PREFIX;
+ (NSString *) ADVERT_INFO_PREFIX;
+ (NSString *) ADVERT_TOTAL_COUNT;
@end
