/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


#import "RedisKey.h"

static NSString * NULL_VALUE = @"null";
static NSString * RSCCOUNTY = @"rscCounty";
static NSString * USER_PREFIX = @"user_";
static NSString * BLACK_LIST_PREFIX = @"h_user_black_list";
static NSString * ADVERT_INFO_PREFIX = @"ADVERT_INFO_PREFIX";
static NSString * ADVERT_TOTAL_COUNT = @"ADVERT_TOTAL_COUNT";

@implementation RedisKeyConstants
+ (void) initialize {
}
+ (NSString *) NULL_VALUE{
  return NULL_VALUE;
}
+ (NSString *) RSCCOUNTY{
  return RSCCOUNTY;
}
+ (NSString *) USER_PREFIX{
  return USER_PREFIX;
}
+ (NSString *) BLACK_LIST_PREFIX{
  return BLACK_LIST_PREFIX;
}
+ (NSString *) ADVERT_INFO_PREFIX{
  return ADVERT_INFO_PREFIX;
}
+ (NSString *) ADVERT_TOTAL_COUNT{
  return ADVERT_TOTAL_COUNT;
}
@end

