/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


enum ReturnCode {
  ReturnCode_UNKNOWN = 100,
  ReturnCode_OK = 200,
  ReturnCode_CLINET_ERROR = 400,
  ReturnCode_SERVER_ERROR = 500,
  ReturnCode_SERVER_BUSY = 501,
  ReturnCode_MISSING_ARG = 401,
  ReturnCode_C_EXCEPTION = 600,
  ReturnCode_C_DATANULL = 601,
  ReturnCode_C_IOEXCEPTION = 602,
  ReturnCode_P_EXCEPTION = 900,
  ReturnCode_S_RULES_ERROR = 800,
  ReturnCode_S_USER_NOT_FOUND = 801,
  ReturnCode_S_MOBILE_ILLEGAL = 802,
  ReturnCode_S_SECRET_ILLEGAL = 903,
  ReturnCode_S_SECRET_TIMEOUT = 902,
  ReturnCode_S_APPKEY_NOT_FOUND = 904
};

@interface ReturnCodeConstants : NSObject {
}
@end
