/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface LoginInput : NSObject <TBase, NSCoding> {
  NSString * __userName;
  NSString * __password;
  NSString * __version;

  BOOL __userName_isset;
  BOOL __password_isset;
  BOOL __version_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=userName, setter=setUserName:) NSString * userName;
@property (nonatomic, retain, getter=password, setter=setPassword:) NSString * password;
@property (nonatomic, retain, getter=version, setter=setVersion:) NSString * version;
#endif

- (id) init;
- (id) initWithUserName: (NSString *) userName password: (NSString *) password version: (NSString *) version;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) userName;
- (void) setUserName: (NSString *) userName;
#endif
- (BOOL) userNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) password;
- (void) setPassword: (NSString *) password;
#endif
- (BOOL) passwordIsSet;

#if !__has_feature(objc_arc)
- (NSString *) version;
- (void) setVersion: (NSString *) version;
#endif
- (BOOL) versionIsSet;

@end

@interface LoginOutput : NSObject <TBase, NSCoding> {
  int32_t __userId;
  int32_t __shardId;
  NSString * __userName;
  NSString * __email;
  NSString * __mobile;
  NSString * __cardHolderName;
  NSString * __idNumber;
  NSString * __password;
  int32_t __gender;
  int32_t __userType;
  int32_t __status;
  int32_t __returnCode;

  BOOL __userId_isset;
  BOOL __shardId_isset;
  BOOL __userName_isset;
  BOOL __email_isset;
  BOOL __mobile_isset;
  BOOL __cardHolderName_isset;
  BOOL __idNumber_isset;
  BOOL __password_isset;
  BOOL __gender_isset;
  BOOL __userType_isset;
  BOOL __status_isset;
  BOOL __returnCode_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=userId, setter=setUserId:) int32_t userId;
@property (nonatomic, getter=shardId, setter=setShardId:) int32_t shardId;
@property (nonatomic, retain, getter=userName, setter=setUserName:) NSString * userName;
@property (nonatomic, retain, getter=email, setter=setEmail:) NSString * email;
@property (nonatomic, retain, getter=mobile, setter=setMobile:) NSString * mobile;
@property (nonatomic, retain, getter=cardHolderName, setter=setCardHolderName:) NSString * cardHolderName;
@property (nonatomic, retain, getter=idNumber, setter=setIdNumber:) NSString * idNumber;
@property (nonatomic, retain, getter=password, setter=setPassword:) NSString * password;
@property (nonatomic, getter=gender, setter=setGender:) int32_t gender;
@property (nonatomic, getter=userType, setter=setUserType:) int32_t userType;
@property (nonatomic, getter=status, setter=setStatus:) int32_t status;
@property (nonatomic, getter=returnCode, setter=setReturnCode:) int32_t returnCode;
#endif

- (id) init;
- (id) initWithUserId: (int32_t) userId shardId: (int32_t) shardId userName: (NSString *) userName email: (NSString *) email mobile: (NSString *) mobile cardHolderName: (NSString *) cardHolderName idNumber: (NSString *) idNumber password: (NSString *) password gender: (int32_t) gender userType: (int32_t) userType status: (int32_t) status returnCode: (int32_t) returnCode;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) userId;
- (void) setUserId: (int32_t) userId;
#endif
- (BOOL) userIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) shardId;
- (void) setShardId: (int32_t) shardId;
#endif
- (BOOL) shardIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) userName;
- (void) setUserName: (NSString *) userName;
#endif
- (BOOL) userNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) email;
- (void) setEmail: (NSString *) email;
#endif
- (BOOL) emailIsSet;

#if !__has_feature(objc_arc)
- (NSString *) mobile;
- (void) setMobile: (NSString *) mobile;
#endif
- (BOOL) mobileIsSet;

#if !__has_feature(objc_arc)
- (NSString *) cardHolderName;
- (void) setCardHolderName: (NSString *) cardHolderName;
#endif
- (BOOL) cardHolderNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) idNumber;
- (void) setIdNumber: (NSString *) idNumber;
#endif
- (BOOL) idNumberIsSet;

#if !__has_feature(objc_arc)
- (NSString *) password;
- (void) setPassword: (NSString *) password;
#endif
- (BOOL) passwordIsSet;

#if !__has_feature(objc_arc)
- (int32_t) gender;
- (void) setGender: (int32_t) gender;
#endif
- (BOOL) genderIsSet;

#if !__has_feature(objc_arc)
- (int32_t) userType;
- (void) setUserType: (int32_t) userType;
#endif
- (BOOL) userTypeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) status;
- (void) setStatus: (int32_t) status;
#endif
- (BOOL) statusIsSet;

#if !__has_feature(objc_arc)
- (int32_t) returnCode;
- (void) setReturnCode: (int32_t) returnCode;
#endif
- (BOOL) returnCodeIsSet;

@end

@interface GetUserInput : NSObject <TBase, NSCoding> {
  int32_t __userId;
  NSString * __version;

  BOOL __userId_isset;
  BOOL __version_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=userId, setter=setUserId:) int32_t userId;
@property (nonatomic, retain, getter=version, setter=setVersion:) NSString * version;
#endif

- (id) init;
- (id) initWithUserId: (int32_t) userId version: (NSString *) version;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) userId;
- (void) setUserId: (int32_t) userId;
#endif
- (BOOL) userIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) version;
- (void) setVersion: (NSString *) version;
#endif
- (BOOL) versionIsSet;

@end

@interface GetUserOutput : NSObject <TBase, NSCoding> {
  int32_t __userId;
  int32_t __shardId;
  NSString * __userName;
  NSString * __email;
  NSString * __mobile;
  NSString * __cardHolderName;
  NSString * __idNumber;
  NSString * __password;
  int32_t __gender;
  int32_t __userType;
  int32_t __status;
  int32_t __returnCode;

  BOOL __userId_isset;
  BOOL __shardId_isset;
  BOOL __userName_isset;
  BOOL __email_isset;
  BOOL __mobile_isset;
  BOOL __cardHolderName_isset;
  BOOL __idNumber_isset;
  BOOL __password_isset;
  BOOL __gender_isset;
  BOOL __userType_isset;
  BOOL __status_isset;
  BOOL __returnCode_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=userId, setter=setUserId:) int32_t userId;
@property (nonatomic, getter=shardId, setter=setShardId:) int32_t shardId;
@property (nonatomic, retain, getter=userName, setter=setUserName:) NSString * userName;
@property (nonatomic, retain, getter=email, setter=setEmail:) NSString * email;
@property (nonatomic, retain, getter=mobile, setter=setMobile:) NSString * mobile;
@property (nonatomic, retain, getter=cardHolderName, setter=setCardHolderName:) NSString * cardHolderName;
@property (nonatomic, retain, getter=idNumber, setter=setIdNumber:) NSString * idNumber;
@property (nonatomic, retain, getter=password, setter=setPassword:) NSString * password;
@property (nonatomic, getter=gender, setter=setGender:) int32_t gender;
@property (nonatomic, getter=userType, setter=setUserType:) int32_t userType;
@property (nonatomic, getter=status, setter=setStatus:) int32_t status;
@property (nonatomic, getter=returnCode, setter=setReturnCode:) int32_t returnCode;
#endif

- (id) init;
- (id) initWithUserId: (int32_t) userId shardId: (int32_t) shardId userName: (NSString *) userName email: (NSString *) email mobile: (NSString *) mobile cardHolderName: (NSString *) cardHolderName idNumber: (NSString *) idNumber password: (NSString *) password gender: (int32_t) gender userType: (int32_t) userType status: (int32_t) status returnCode: (int32_t) returnCode;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) userId;
- (void) setUserId: (int32_t) userId;
#endif
- (BOOL) userIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) shardId;
- (void) setShardId: (int32_t) shardId;
#endif
- (BOOL) shardIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) userName;
- (void) setUserName: (NSString *) userName;
#endif
- (BOOL) userNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) email;
- (void) setEmail: (NSString *) email;
#endif
- (BOOL) emailIsSet;

#if !__has_feature(objc_arc)
- (NSString *) mobile;
- (void) setMobile: (NSString *) mobile;
#endif
- (BOOL) mobileIsSet;

#if !__has_feature(objc_arc)
- (NSString *) cardHolderName;
- (void) setCardHolderName: (NSString *) cardHolderName;
#endif
- (BOOL) cardHolderNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) idNumber;
- (void) setIdNumber: (NSString *) idNumber;
#endif
- (BOOL) idNumberIsSet;

#if !__has_feature(objc_arc)
- (NSString *) password;
- (void) setPassword: (NSString *) password;
#endif
- (BOOL) passwordIsSet;

#if !__has_feature(objc_arc)
- (int32_t) gender;
- (void) setGender: (int32_t) gender;
#endif
- (BOOL) genderIsSet;

#if !__has_feature(objc_arc)
- (int32_t) userType;
- (void) setUserType: (int32_t) userType;
#endif
- (BOOL) userTypeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) status;
- (void) setStatus: (int32_t) status;
#endif
- (BOOL) statusIsSet;

#if !__has_feature(objc_arc)
- (int32_t) returnCode;
- (void) setReturnCode: (int32_t) returnCode;
#endif
- (BOOL) returnCodeIsSet;

@end

@protocol UserService <NSObject>
- (LoginOutput *) login: (LoginInput *) input;  // throws TException
- (GetUserOutput *) getUser: (GetUserInput *) input;  // throws TException
@end

@interface UserServiceClient : NSObject <UserService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface UserServiceProcessor : NSObject <TProcessor> {
  id <UserService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithUserService: (id <UserService>) service;
- (id<UserService>) service;
@end

@interface UserServiceConstants : NSObject {
}
@end
