<?php
namespace application\libraries\CommonService;

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


class ServiceMainInput {
  static $_TSPEC;

  public $serviceName = null;
  public $methodName = null;
  public $secretArgs = null;
  public $jsonArgs = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'serviceName',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'methodName',
          'type' => TType::STRING,
          ),
        3 => array(
          'var' => 'secretArgs',
          'type' => TType::STRING,
          ),
        4 => array(
          'var' => 'jsonArgs',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['serviceName'])) {
        $this->serviceName = $vals['serviceName'];
      }
      if (isset($vals['methodName'])) {
        $this->methodName = $vals['methodName'];
      }
      if (isset($vals['secretArgs'])) {
        $this->secretArgs = $vals['secretArgs'];
      }
      if (isset($vals['jsonArgs'])) {
        $this->jsonArgs = $vals['jsonArgs'];
      }
    }
  }

  public function getName() {
    return 'ServiceMainInput';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->serviceName);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->methodName);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->secretArgs);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 4:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->jsonArgs);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ServiceMainInput');
    if ($this->serviceName !== null) {
      $xfer += $output->writeFieldBegin('serviceName', TType::STRING, 1);
      $xfer += $output->writeString($this->serviceName);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->methodName !== null) {
      $xfer += $output->writeFieldBegin('methodName', TType::STRING, 2);
      $xfer += $output->writeString($this->methodName);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->secretArgs !== null) {
      $xfer += $output->writeFieldBegin('secretArgs', TType::STRING, 3);
      $xfer += $output->writeString($this->secretArgs);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->jsonArgs !== null) {
      $xfer += $output->writeFieldBegin('jsonArgs', TType::STRING, 4);
      $xfer += $output->writeString($this->jsonArgs);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}


